// export enum Ages {
//   TRIBAL = 'tribal_age',
//   STONE = 'stone_age',
//   BRONZE = 'bronze_age',
//   IRON = 'iron_age',
//   CLASSICAL = 'classical_age',
//   HELLENISTIC = 'hellenistic_age',
//   ROMAN = 'roman_age',
//   EARLY_MEDIEVAL = 'early_medieval',
//   HIGH_MEDIEVAL = 'high_medieval',
//   LATE_MEDIEVAL = 'late_medieval',
//   RENAISSANCE = 'renaissance_age',
//   INDUSTRIAL = 'industrial_revolution',
//   GLOBAL_CONFLICT = 'global_conflict',
//   COLD_WAR = 'cold_war_age',
//   SPACE = 'space_age',
//   AI = 'ai_era',
//   GALACTIC = 'galactic_age',
// }
